# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_bank_app', '0002_auto_20160304_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='description',
        ),
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
