# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_bank_app', '0004_auto_20160304_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('d', 'deposit'), ('w', 'withdrawal'), ('t', 'transfer')], max_length=10),
        ),
    ]
